repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: check-yaml
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://gitlab.com/PyCQA/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
